--Up
CREATE TABLE IF NOT EXISTS url (
    id SERIAL PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_code VARCHAR(10) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--Down
DROP TABLE IF EXISTS url;